FROM golang:1.21.5-alpine3.19 as builder
WORKDIR /app

COPY . /app

WORKDIR /app/sidecar
RUN go build -o sidecar

FROM alpine:3.19
WORKDIR /root/

COPY --from=builder /app/sidecar/sidecar .


# CMD ["./sidecar"]
CMD ./sidecar

#docker run -e rabbitMQServerIP=host.docker.internal -d your_image_name
#docker build -f Dockerfile.sidecar -t myproject/sidecar .
#docker run --name documents_sidecar_ms -it myproject/sidecar