FROM golang:1.21.5-alpine3.19 as builder
WORKDIR /app

COPY . /app

WORKDIR /app/server
RUN go build -o server

FROM alpine:3.19
WORKDIR /root/

COPY --from=builder /app/server/server .

EXPOSE 3012

CMD ["./server"]

#docker build -f Dockerfile.server -t myproject/server .
#docker run --name documents_ms -p 3012:3012 -it myproject/server
