.PHONY: start
start:
	@echo "sidecar"
	@go build -o ../bin/ 
	@echo "Running the application..."
	@../bin/sidecar.exe

# Compilado con gnuWin32
#start cmd /c "docker start some-rabbit && timeout /t 60 && cd HighQualityMicroservice && make"
